### ISSUE TITLE
It takes around 30 min to recreate a node

### ISSUE THREAD

**Issue by jia-jerry** [gardener/machine-controller-manager-provider-alicloud#18]
**What happened**:
In a running shoot, after a VM is deleted (From AliCloud Console), it took around 30 for MCM to recreate a new node.
**What you expected to happen**:
It will be recovered as fast as possible.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by shaoyongfeng** [comment]
After investigation, I think it's expected behavior.
When user deletes a VM in iaas account, it takes 2~3 minutes for k8s to detect problem for this node and reflects in status as unknown. Then this node will be removed from cluster.
Then health check of MCM then detects this problem and update status of machine as unknown.
There is a startup option of MCM which specifies the  unhealthy timeout period. By default it's 10 minutes.

After 10 minutes, MCM updates status of this machine to failed  and then triggers the deletion flow.
Meanwhile MCM also finds replicas is not as expected as machineset, MCM will trigger the. creation flow. It takes ~2 minutes to spin up a new VM. 

So in total, it takes 3+10+2 =15 minutes to detect machine issue and fix it for best case.

**Comment by jia-jerry** [comment]
We should check returned error [here](https://github.com/gardener/machine-controller-manager-provider-alicloud/blob/master/pkg/alicloud/machine_controller.go#L164). If it is not found, we simply return success.

**Comment by shaoyongfeng** [comment]
No, I don't think it's a problem and won't block machine recreation. Actually the not found  error is caught outside [here](https://github.com/gardener/machine-controller-manager-provider-alicloud/blob/master/vendor/github.com/gardener/machine-controller-manager/pkg/util/provider/machinecontroller/machine_util.go#L1096-L1099)
From provider point of, it should return the error back to caller if caller passes non-existing machine ID to it

**Comment by shaoyongfeng** [comment]
After double checking together with Emoin, There won't be a problem of getvmstatus even though ECS doesn't exist.  In such case, it just skips deletevm step and go to deletenode directly.
So the scenario in description works well.
We need to double check with original reporter what's the exact step he did.
